# Generated by Django 5.2.5 on 2025-08-12 04:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('science', '理科'), ('social', '社会')], max_length=10, unique=True, verbose_name='教科コード')),
                ('label_ja', models.CharField(max_length=20, verbose_name='教科名')),
            ],
            options={
                'verbose_name': '教科',
                'verbose_name_plural': '教科',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_year', models.CharField(max_length=10, verbose_name='学年')),
                ('category', models.CharField(max_length=50, verbose_name='カテゴリ')),
                ('unit_key', models.CharField(max_length=100, unique=True, verbose_name='単元キー')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='quiz_app.subject', verbose_name='教科')),
            ],
            options={
                'verbose_name': '単元',
                'verbose_name_plural': '単元',
                'unique_together': {('subject', 'grade_year', 'category')},
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.PositiveIntegerField(choices=[(10, '10問'), (20, '20問')], verbose_name='問題数')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始時刻')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('total_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='総得点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to='quiz_app.unit', verbose_name='単元')),
            ],
            options={
                'verbose_name': 'クイズセッション',
                'verbose_name_plural': 'クイズセッション',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=50, verbose_name='元データID')),
                ('text', models.TextField(verbose_name='問題文')),
                ('correct_answer', models.TextField(verbose_name='正解')),
                ('accepted_alternatives', models.JSONField(blank=True, default=list, verbose_name='別解')),
                ('requires_unit_label', models.BooleanField(default=False, verbose_name='単位ラベル必要')),
                ('unit_label_text', models.CharField(blank=True, max_length=20, verbose_name='単位ラベル')),
                ('parts_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='解答欄数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.unit', verbose_name='単元')),
            ],
            options={
                'verbose_name': '問題',
                'verbose_name_plural': '問題',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.PositiveIntegerField(verbose_name='問題数')),
                ('publish_scope', models.CharField(choices=[('class', 'クラス'), ('school', '学校')], max_length=10, verbose_name='公開範囲')),
                ('scope_prefecture', models.CharField(max_length=10, verbose_name='対象都道府県')),
                ('scope_school', models.CharField(max_length=100, verbose_name='対象学校')),
                ('scope_class_name', models.CharField(blank=True, max_length=50, verbose_name='対象クラス')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開中')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('public_slug', models.CharField(max_length=100, unique=True, verbose_name='公開スラッグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='quiz_app.unit', verbose_name='単元')),
            ],
            options={
                'verbose_name': '宿題',
                'verbose_name_plural': '宿題',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='解答内容')),
                ('is_correct', models.BooleanField(verbose_name='正解')),
                ('time_spent_sec', models.PositiveIntegerField(verbose_name='解答時間（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz_app.question', verbose_name='問題')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz_app.quizsession', verbose_name='セッション')),
            ],
            options={
                'verbose_name': 'クイズ解答記録',
                'verbose_name_plural': 'クイズ解答記録',
                'indexes': [models.Index(fields=['question'], name='quiz_app_qu_questio_e69902_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['unit', 'source_id'], name='quiz_app_qu_unit_id_e354fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('unit', 'source_id')},
        ),
    ]
