# Generated by Django 5.2.5 on 2025-08-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_quizsession_question_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, default=list, verbose_name='選択肢'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', '記述問題'), ('choice', '選択問題')], default='text', max_length=10, verbose_name='問題タイプ'),
        ),
    ]
