# Generated by Django 5.2.5 on 2025-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_question_choices_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='choice_mappings',
            field=models.JSONField(blank=True, default=dict, verbose_name='選択肢並べ替えマッピング'),
        ),
    ]
