# Generated by Django 5.2.5 on 2025-08-12 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='テンプレート名')),
                ('template_file', models.FileField(upload_to='pdf_templates/', verbose_name='テンプレートファイル')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'PDFテンプレート',
                'verbose_name_plural': 'PDFテンプレート',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=50, verbose_name='データタイプ')),
                ('scope', models.CharField(max_length=100, verbose_name='スコープ')),
                ('data', models.JSONField(verbose_name='データ')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='計算日時')),
            ],
            options={
                'verbose_name': '分析データ',
                'verbose_name_plural': '分析データ',
                'unique_together': {('data_type', 'scope')},
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '情報'), ('warning', '警告'), ('error', 'エラー')], max_length=10, verbose_name='レベル')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'システムログ',
                'verbose_name_plural': 'システムログ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='XLSMUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('science', '理科'), ('social', '社会')], max_length=10, verbose_name='教科')),
                ('file', models.FileField(upload_to='xlsm_files/', verbose_name='ファイル')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='処理日時')),
                ('status', models.CharField(choices=[('pending', '処理待ち'), ('processing', '処理中'), ('completed', '完了'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='ステータス')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xlsm_uploads', to=settings.AUTH_USER_MODEL, verbose_name='アップロード者')),
            ],
            options={
                'verbose_name': 'XLSMアップロード',
                'verbose_name_plural': 'XLSMアップロード',
            },
        ),
    ]
